name: Security Pipeline (DevSecOps)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:

  # 1. Сборка проекта
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build || echo "No build script, skipping"

  # 2. Snyk SCA (сканирование зависимостей)
  snyk-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Snyk SCA Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --fail-on=all

  # 3. Gitleaks Secret Scan (поиск секретов)
  gitleaks-secret-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks Filesystem Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            zricethezav/gitleaks:latest \
            dir /repo --redact --verbose --exit-code 1

  # 4. CodeQL SAST (статический анализ кода)
  codeql-sast:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      security-events: write   # требуется для загрузки SARIF-отчёта
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
  # 5. DAST (OWASP ZAP)
  dast-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
  
      - name: Install dependencies
        run: npm install
  
      - name: Start application
        run: |
          npm start &
          sleep 15
  
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm \
            --user root \
            --network="host" \
            -v ${{ github.workspace }}:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:3000 \
            -r zap-report.html
            -I || true
            
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
